### ISSUE TITLE
CI Tests broken

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-output-s3#36] opened 2015-09-23 13:37 UTC
From: http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Outputs/job/logstash-plugin-output-s3-unit/10/

```
Bundle complete! 5 Gemfile dependencies, 47 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..FF.FF......F.FFFF
  An error occurred in an after hook
    NoMethodError: undefined method `teardown' for #<LogStash::Outputs::S3:0x69058404>
    occurred at /home/jenkins/workspace/logstash-plugin-output-s3-unit/jdk/JDK7/nodes/metal-pool/spec/outputs/s3_spec.rb:197:in `(root)'

F..

Failures:

  1) LogStash::Outputs::S3#receive should send the event through the codecs
     Failure/Error: s3.register
     NameError:
       uninitialized constant Stud::Task
     # ./lib/logstash/outputs/s3.rb:363:in `configure_upload_workers'
     # ./lib/logstash/outputs/s3.rb:362:in `configure_upload_workers'
     # ./lib/logstash/outputs/s3.rb:204:in `register'
     # ./spec/outputs/s3_spec.rb:261:in `(root)'

  2) LogStash::Outputs::S3#register should create the tmp directory if it doesn't exist
     Failure/Error: s3.register
     NameError:
       uninitialized constant Stud::Task
     # ./lib/logstash/outputs/s3.rb:363:in `configure_upload_workers'
     # ./lib/logstash/outputs/s3.rb:362:in `configure_upload_workers'
     # ./lib/logstash/outputs/s3.rb:204:in `register'
     # ./spec/outputs/s3_spec.rb:50:in `(root)'

  3) LogStash::Outputs::S3#write_on_bucket should prefix the file on the bucket if a prefix is specified
     Failure/Error: s3.register
     NameError:
       uninitialized constant Stud::Task
```

**Comment by jsvd** [comment] 2015-09-23 13:38
duplicate of #34  I think?

**Comment by ph** [comment] 2015-09-23 13:39
yes dupe of #34

**Comment by purbon** [comment] 2015-09-23 13:39
@ph don't think is duplicated, test are broken there, not hanging.

**Comment by jsvd** [comment] 2015-09-23 13:40
when I did #35 I saw both things happen. one is consequence of bad stud requirement, the other due to lack of renaming + new geneartor plugin

**Comment by ph** [comment] 2015-09-23 13:42
@jsvd Yup, I had the same behavior.

**Comment by ph** [comment] 2015-10-30 13:49
This is back, checking it.

**Closed** 2015-10-30 15:23 UTC
Labels: bug, tests-infra
