### ISSUE TITLE
Limit retry interval

### ISSUE THREAD

**Issue by Sjaak01** [logstash-plugins/logstash-output-s3#169] opened 2018-02-20 07:11 UTC
Hi,

Is it possible to set/limit the retry interval when connecting to s3 fails?

In my case I have a firewall blocking access to s3 over one of my WAN links (low bandwidth, very high costs). However the constant retrying is generating several hundreds MB of DNS traffic an hour.

If a upload fails I don't want a retry for another hour or try uploading again when the next file is due.

**Comment by idsvandermolen** [comment] 2019-02-06 08:03
duplicate of https://github.com/logstash-plugins/logstash-output-s3/issues/160

**Closed** 2020-02-07 17:01 UTC
